<a href="https://colab.research.google.com/github/MathMachado/DSWP/blob/master/Notebooks/NB03__Numeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1><b><i>NÚMEROS</i></b></h1></center>



# **AGENDA**:
> Nesta capítulo, vamos abordar os seguintes assuntos:

* Operadores aritméticos
* Funções round(), floor(), ceil() e trunc()
* Operadores para comparação
* Operadores de atribuição
* Wrap Up
* Exercícios

___
# **NOTAS E OBSERVAÇÕES**

___
# **NÚMEROS**
> Basicamente, há dois tipos de números em Python:

* float point
    * Exemplo: temperatura, altura, etc
    
* Integer
    * Exemplo: idade, dia do mês, etc...


___
# **OPERADORES ARITMÉTICOS**
> Considere as variáveis i_numero1 = 7 e i_numero2 = 3 abaixo, então:

| Operador | Descrição | Exemplo | Operação | Resultado |
|---|---|---|---|---|
| +  | Adição | resultado = numero1 + numero2 | resultado = 7 + 3 | resultado = 10 |
| -  | Subtração | resultado = numero1 - numero2 | resultado = 7 - 3 | resultado = 4|
| /  | Divisão | resultado = numero1 / numero2 | resultado = 7 / 3 | resultado = 2.333... |
| %  | Resto da Divisão | resultado = numero1 % numero2 | resultado = 7%3 | resultado = 1 | 
| *  | Multiplicação | resultado = numero1 * numero2 | resultado = 7 * 3 | resultado = 21 |
| //  | Quociente da Divisão | resultado = numero1 // numero2 | resultado = 7 // 3 | resultado = 2 |
| **  | Potência | resultado = numero1 ** numero2 | resultado = 7\*7\*7 | resultado = 343|

> Nas operações matemáticas de divisão, chamamos:

    * 7 de dividendo (o número que se quer dividir);
    * 3 de divisor;
    * 2 é o quociente ou resultado, dado por 7 // 3;
    * 1 é o resto, dado por 7 % 3

Confirma na imagem a seguir os elementos da Divisão:

![Divisao](https://github.com/MathMachado/Materials/blob/master/Divisao.png?raw=true)

Conforme vimos acima, temos que numero1 = 7 e numero2 = 3. Vamos aplicar os conhecimentos que acabamos de aprender:

In [ ]:
numero1 = 7
numero2 = 3

Qual o valor de C nas expressões abaixo?

In [ ]:
resultado = numero1 + numero2
f'O valor de resultado é: {resultado}'

'O valor de C é: 10'

In [ ]:
resultado = numero1 - numero2
f'O valor de resultado é: {resultado}'

'O valor de C é: 4'

In [ ]:
resultado = numero1 * numero2
f'O valor de resultado é: {resultado}'

'O valor de C é: 21'

## Funções round(), floor(), ceil() e trunc()

### Exemplo 1

In [ ]:
resultado = numero2/numero1

# Importa a biblioteca math
import math

resultado_round2 = round(resultado, 2) # Arredonda resultado para 2 casas decimais.
resultado_round4 = round(resultado, 4) # Arredonda resultado para 4 casas decimais.
resultado_floor = math.floor(resultado) # Retorna o maior valor inteiro menor ou igual a resultado.
resultado_ceil = math.ceil(resultado) # Retorna o menor valor inteiro maior ou igual a resultado.
resultado_trunc = math.trunc(resultado) # Retorna resultado truncado para um inteiro

In [ ]:
# Valor de resultado com 17 casas decimais:
f'{resultado}'

'0.42857142857142855'

In [ ]:
# Valor de resultado com 2 casas decimais:
f'{resultado_round2}'

'0.43'

In [ ]:
# Valor de resultado com 4 casas decimais:
f'{resultado_round4}'

'0.4286'

In [ ]:
# Retorna o maior valor inteiro menor ou igual a resultado:
f'{resultado_floor}'

'0'

In [ ]:
# Retorna o menor valor inteiro maior ou igual a resultado:
f'{resultado_ceil}'

'1'

In [ ]:
# Retorna a parte inteira de resultado:
f'{resultado_trunc}'

'0'

### Exemplo 2

In [ ]:
resultado = 13 / 3

# Importa a biblioteca math
import math

resultado_round2 = round(reultado, 2) # Arredonda reultado para 2 casas decimais.
resultado_round4 = round(reultado, 4) # Arredonda reultado para 4 casas decimais.
resultado_floor = math.floor(reultado) # Retorna o maior valor inteiro menor ou igual a reultado.
resultado_ceil = math.ceil(reultado) # Retorna o menor valor inteiro maior ou igual a reultado.
resultado_trunc = math.trunc(reultado) # Retorna reultado truncado para um inteiro

... Novamente, mas desta vez, definindo 2 casas decimais:

In [ ]:
f'O valor de resultado é: {reultado:{8}.{2}}'

'O valor de C é:      4.3'

In [ ]:
# Valor de reultado com 2 casas decimais:
f'{resultado_round2}'

'4.33'

In [ ]:
# Valor de reultado com 4 casas decimais:
f'{resultado_round4}'

'4.3333'

In [ ]:
# Retorna o maior valor inteiro menor ou igual a reultado:
f'{resultado_floor}'

'4'

In [ ]:
# Retorna o menor valor inteiro maior ou igual a reultado:
f'{resultado_ceil}'

'5'

In [ ]:
# Retorna a parte inteira de reultado:
f'{resultado_trunc}'

'4'

___
# **OPERADORES PARA COMPARAÇÃO**

* Considere as variáveis numero1 = 7, numero2 = 3 e o vetor x abaixo, então:

| Operador | Exemplo | Descrição | Resultado |
|---|---|---|---|
| == | numero1 == numero2 | 7 é igual a 3? | False |
| != | numero1 != numero2 | 7 é diferente de 3? | True |
| >  | numero1 > numero2 | 7 é maior que 3? | True |
| < | numero1 < numero2 | 7 é menor que 3? | False | 
| >= | numero1 >= numero2 | 7 é maior ou igual a 3? | True |
| <= | numero1 <= numero2 | 7 é menor ou igual a 3? | False |

Vamos aplicar os conhecimentos que acabamos de aprender:

In [ ]:
numero1 = 7
numero2 = 3

Array x:

In [ ]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Qual o resultadodas expressões a seguir:

In [ ]:
numero1 == numero2

In [ ]:
numero1 != numero2

In [ ]:
numero1 > numero2

In [ ]:
numero1 < numero2

In [ ]:
numero1 >= numero2

In [ ]:
numero1 <= numero2

Qual o resultado das expressões a seguir:

In [ ]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Da mesma forma, se tivermos a matrix abaixo:

In [ ]:
r = np.random.RandomState(20111974)
x = r.randint(10, size= (3, 4))
x

array([[8, 8, 2, 8],
       [9, 1, 8, 0],
       [4, 2, 0, 8]])

Qual o resultado das expressões a seguir:

In [ ]:
x == 3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
x != 3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
x < 3

array([[False, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False]])

In [ ]:
x > 3

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True]])

___
# **OPERADORES DE ATRIBUIÇÃO**

| Operador | Exemplo | Operação Equivalente | 
|---|---|---|
| = | resultado = numero1 + numero2 |
| += | resultado += numero2 | resultado = resultado + numero2 |
| -= | resultado -= numero2 | resultado = resultado - numero2 |
| *= | resultado *= numero2 | resultado = resultado * numero2 |
| /= | resultado /= numero2 | resultado = resultado / numero2 |
| %= | resultado %= numero2 | resultado = resultado % numero2 |
| **= | resultado *= numero2 | resultado = resultado ** numero2 |
| //= | resultado // = numero2 | resultado = resultado // numero2 |

Considere numero1 = 7 e numero2 = 3 e vamos praticar os conhecimentos que acabamos de aprender:

In [ ]:
numero1 = 7
numero2 = 3

Qual o valor de C nas expressões a seguir:

In [ ]:
resultado = numero1 + numero2
f'O valor de resultado é: {resultado}'

In [ ]:
resultado += numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado -= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado *= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado /= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado %= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado **= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado //= numero1
f'O valor de resultado é: {resultado}'

___
# **WRAP UP**

___
# **EXERCÍCIOS**