<a href="https://colab.research.google.com/github/MathMachado/DSWP/blob/master/Notebooks/NB03__Operadores%20e%20Fun%C3%A7%C3%B5es%20Matem%C3%A1ticas%20essenciais%20no%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1><b><i>Operadores e Funções Matemáticas essenciais no Python
</i></b></h1></center>



# **AGENDA**:
> Neste capítulo você irá aprofundar seu conhecimento nos operadores e funções matemáticas fundamentais do Python, ferramentas indispensáveis para qualquer programador. Abordaremos os seguintes tópicos:

* Operadores aritméticos: Entenda como utilizar operadores básicos como adição (+), subtração (-), multiplicação (*), divisão (/), módulo (%), exponenciação (**) e divisão inteira (//).
* Funções matemáticas: Aprenda a aplicar funções como round(), floor(), ceil() e trunc() para manipular números e controlar o arredondamento em suas operações.
* Operadores de comparação: Descubra como comparar valores utilizando operadores como igual a (==), diferente de (!=), maior que (>), menor que (<), maior ou igual a (>=) e menor ou igual a (<=).
* Operadores de atribuição: Veja como simplificar atribuições e atualizações de valores em variáveis com operadores como =, +=, -=, *=, /=, entre outros.

Finalizaremos com um wrap-up para revisar os conceitos aprendidos, garantindo que você esteja pronto para aplicar esses conhecimentos em seus projetos. Além disso, disponibilizaremos exercícios práticos para você consolidar seu aprendizado.

Este vídeo é perfeito para iniciantes e para quem deseja reforçar suas habilidades em operações matemáticas e lógicas no Python, tornando seu código mais eficiente e eficaz.


___
# **NOTAS E OBSERVAÇÕES**

___
# **NÚMEROS**
> Basicamente, há dois tipos de números em Python:

* float point
    * Exemplo: temperatura, altura, etc
    
* Integer
    * Exemplo: idade, dia do mês, etc...


___
# **OPERADORES ARITMÉTICOS**
> Considere as variáveis i_numero1 = 7 e i_numero2 = 3 abaixo, então:

| Operador | Descrição | Exemplo | Operação | Resultado |
|---|---|---|---|---|
| +  | Adição | resultado = numero1 + numero2 | resultado = 7 + 3 | resultado = 10 |
| -  | Subtração | resultado = numero1 - numero2 | resultado = 7 - 3 | resultado = 4|
| /  | Divisão | resultado = numero1 / numero2 | resultado = 7 / 3 | resultado = 2.333... |
| %  | Resto da Divisão | resultado = numero1 % numero2 | resultado = 7%3 | resultado = 1 |
| *  | Multiplicação | resultado = numero1 * numero2 | resultado = 7 * 3 | resultado = 21 |
| //  | Quociente da Divisão | resultado = numero1 // numero2 | resultado = 7 // 3 | resultado = 2 |
| **  | Potência | resultado = numero1 ** numero2 | resultado = 7\*7\*7 | resultado = 343|

> Nas operações matemáticas de divisão, chamamos:

    * 7 de dividendo (o número que se quer dividir);
    * 3 de divisor;
    * 2 é o quociente ou resultado, dado por 7 // 3;
    * 1 é o resto, dado por 7 % 3

Confirma na imagem a seguir os elementos da Divisão:

![Divisao](https://github.com/MathMachado/Materials/blob/master/Divisao.png?raw=true)

Conforme vimos acima, temos que numero1 = 7 e numero2 = 3. Vamos aplicar os conhecimentos que acabamos de aprender:

In [1]:
numero1 = 7
numero2 = 3

Qual o valor de C nas expressões abaixo?

In [2]:
resultado = numero1 + numero2
f'O valor de resultado é: {resultado}'

'O valor de resultado é: 10'

In [ ]:
resultado = numero1 - numero2
f'O valor de resultado é: {resultado}'

'O valor de C é: 4'

In [ ]:
resultado = numero1 * numero2
f'O valor de resultado é: {resultado}'

'O valor de C é: 21'

## Funções round(), floor(), ceil() e trunc()

### Exemplo 1

In [3]:
resultado = numero2/numero1

# Importa a biblioteca math
import math

resultado_round2 = round(resultado, 2) # Arredonda resultado para 2 casas decimais.
resultado_round4 = round(resultado, 4) # Arredonda resultado para 4 casas decimais.
resultado_floor = math.floor(resultado) # Retorna o maior valor inteiro menor ou igual a resultado.
resultado_ceil = math.ceil(resultado) # Retorna o menor valor inteiro maior ou igual a resultado.
resultado_trunc = math.trunc(resultado) # Retorna resultado truncado para um inteiro

In [4]:
# Valor de resultado com 17 casas decimais:
f'{resultado}'

'0.42857142857142855'

In [5]:
# Valor de resultado com 2 casas decimais:
f'{resultado_round2}'

'0.43'

In [6]:
# Valor de resultado com 4 casas decimais:
f'{resultado_round4}'

'0.4286'

In [7]:
# Retorna o maior valor inteiro menor ou igual a resultado:
f'{resultado_floor}'

'0'

In [8]:
# Retorna o menor valor inteiro maior ou igual a resultado:
f'{resultado_ceil}'

'1'

In [9]:
# Retorna a parte inteira de resultado:
f'{resultado_trunc}'

'0'

### Exemplo 2

In [11]:
resultado = 13 / 3

# Importa a biblioteca math
import math

resultado_round2 = round(resultado, 2) # Arredonda resultado para 2 casas decimais.
resultado_round4 = round(resultado, 4) # Arredonda resultado para 4 casas decimais.
resultado_floor = math.floor(resultado) # Retorna o maior valor inteiro menor ou igual a resultado.
resultado_ceil = math.ceil(resultado) # Retorna o menor valor inteiro maior ou igual a resultado.
resultado_trunc = math.trunc(resultado) # Retorna resultado truncado para um inteiro

... Novamente, mas desta vez, definindo 2 casas decimais:

In [13]:
f'O valor de resultado é: {resultado:{8}.{2}}'

'O valor de resultado é:      4.3'

In [14]:
# Valor de reultado com 2 casas decimais:
f'{resultado_round2}'

'4.33'

In [15]:
# Valor de reultado com 4 casas decimais:
f'{resultado_round4}'

'4.3333'

In [17]:
# Retorna o maior valor inteiro menor ou igual a reultado:
f'{resultado_floor}'

'4'

In [18]:
# Retorna o menor valor inteiro maior ou igual a reultado:
f'{resultado_ceil}'

'5'

In [19]:
# Retorna a parte inteira de reultado:
f'{resultado_trunc}'

'4'

___
# **OPERADORES PARA COMPARAÇÃO**

* Considere as variáveis numero1 = 7, numero2 = 3 e o vetor x abaixo, então:

| Operador | Exemplo | Descrição | Resultado |
|---|---|---|---|
| == | numero1 == numero2 | 7 é igual a 3? | False |
| != | numero1 != numero2 | 7 é diferente de 3? | True |
| >  | numero1 > numero2 | 7 é maior que 3? | True |
| < | numero1 < numero2 | 7 é menor que 3? | False |
| >= | numero1 >= numero2 | 7 é maior ou igual a 3? | True |
| <= | numero1 <= numero2 | 7 é menor ou igual a 3? | False |

Vamos aplicar os conhecimentos que acabamos de aprender:

In [ ]:
numero1 = 7
numero2 = 3

Array x:

In [ ]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Qual o resultadodas expressões a seguir:

In [ ]:
numero1 == numero2

In [ ]:
numero1 != numero2

In [ ]:
numero1 > numero2

In [ ]:
numero1 < numero2

In [ ]:
numero1 >= numero2

In [ ]:
numero1 <= numero2

Qual o resultado das expressões a seguir:

In [ ]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Da mesma forma, se tivermos a matrix abaixo:

In [ ]:
r = np.random.RandomState(20111974)
x = r.randint(10, size= (3, 4))
x

array([[8, 8, 2, 8],
       [9, 1, 8, 0],
       [4, 2, 0, 8]])

Qual o resultado das expressões a seguir:

In [ ]:
x == 3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
x != 3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
x < 3

array([[False, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False]])

In [ ]:
x > 3

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True]])

___
# **OPERADORES DE ATRIBUIÇÃO**

| Operador | Exemplo | Operação Equivalente |
|---|---|---|
| = | resultado = numero1 + numero2 |
| += | resultado += numero2 | resultado = resultado + numero2 |
| -= | resultado -= numero2 | resultado = resultado - numero2 |
| *= | resultado *= numero2 | resultado = resultado * numero2 |
| /= | resultado /= numero2 | resultado = resultado / numero2 |
| %= | resultado %= numero2 | resultado = resultado % numero2 |
| **= | resultado *= numero2 | resultado = resultado ** numero2 |
| //= | resultado // = numero2 | resultado = resultado // numero2 |

Considere numero1 = 7 e numero2 = 3 e vamos praticar os conhecimentos que acabamos de aprender:

In [ ]:
numero1 = 7
numero2 = 3

Qual o valor de C nas expressões a seguir:

In [ ]:
resultado = numero1 + numero2
f'O valor de resultado é: {resultado}'

In [ ]:
resultado += numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado -= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado *= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado /= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado %= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado **= numero1
f'O valor de resultado é: {resultado}'

In [ ]:
resultado //= numero1
f'O valor de resultado é: {resultado}'

___
# **WRAP UP**

___
# **EXERCÍCIOS**

## **1. Operadores Aritméticos Básicos**

**Descrição:**  
Escreva um programa que solicite ao usuário dois números e, em seguida, calcule e exiba a **soma**, **subtração**, **multiplicação**, **divisão**, **divisão inteira**, **resto da divisão** e **exponenciação** desses números.

**Dicas:**
- Utilize os operadores `+`, `-`, `*`, `/`, `//`, `%` e `**`.
- Certifique-se de tratar a divisão por zero.

---

## **2. Uso das Funções `round()`, `floor()`, `ceil()` e `trunc()`**

**Descrição:**  
Com base no número `7.5678`, aplique as funções `round()`, `floor()`, `ceil()` e `trunc()` e exiba os resultados. Explique as diferenças entre cada função nos comentários do código.

**Dicas:**
- Importe o módulo `math` para usar `floor()`, `ceil()` e `trunc()`.
- Observe como cada função trata a parte decimal do número.

---

## **3. Calculadora de Gorjeta**

**Descrição:**  
Crie um programa que peça ao usuário o valor total de uma conta em um restaurante e a porcentagem da gorjeta que ele deseja dar. Use operadores aritméticos para calcular o valor da gorjeta e o total a pagar.

**Dicas:**
- Converta a porcentagem de gorjeta em um valor decimal (por exemplo, 10% = 0.10).
- Exiba os valores com duas casas decimais usando a função `round()` ou formatando a saída.

---

## **4. Conversão de Temperatura**

**Descrição:**  
Escreva um programa que converta uma temperatura dada em **Celsius** para **Fahrenheit** e **Kelvin**. Utilize operadores aritméticos nas fórmulas de conversão.

**Fórmulas:**
- Fahrenheit = (Celsius × 9/5) + 32
- Kelvin = Celsius + 273.15

**Dicas:**
- Peça ao usuário para inserir a temperatura em Celsius.
- Exiba os resultados das conversões.

---

## **5. Comparação de Números**

**Descrição:**  
Peça ao usuário que insira dois números e use **operadores de comparação** para determinar se o primeiro número é maior, menor ou igual ao segundo número. Exiba mensagens apropriadas para cada caso.

**Dicas:**
- Utilize os operadores `>`, `<` e `==`.
- Use estruturas condicionais (`if`, `elif`, `else`) para exibir as mensagens.

---

## **6. Verificação de Par ou Ímpar**

**Descrição:**  
Escreva um programa que peça um número inteiro ao usuário e use o operador **módulo** (`%`) para determinar se o número é **par** ou **ímpar**. Exiba o resultado.

**Dicas:**
- Um número é par se o resto da divisão por 2 é zero.
- Utilize uma estrutura condicional para verificar o resultado.

---

## **7. Atualização de Valor com Operadores de Atribuição**

**Descrição:**  
Inicie uma variável com o valor `100`. Em seguida, use **operadores de atribuição compostos** para:

- Adicionar 50
- Subtrair 25
- Multiplicar por 2
- Dividir por 5

Exiba o valor da variável após **cada operação**.

**Dicas:**
- Utilize os operadores `+=`, `-=`, `*=`, `/=`.
- Certifique-se de converter para o tipo adequado se necessário (por exemplo, int ou float).

---

## **8. Cálculo de Juros Simples**

**Descrição:**  
Crie um programa que calcule o montante final de uma aplicação financeira de acordo com a fórmula:

```
Montante = Capital + (Capital × Taxa × Tempo)
```

Peça ao usuário para inserir o **capital inicial**, a **taxa de juros** (em decimal) e o **tempo** (em anos). Use operadores aritméticos para realizar o cálculo.

**Dicas:**
- Certifique-se de que a taxa esteja em formato decimal (por exemplo, 5% = 0.05).
- Exiba o montante final formatado com duas casas decimais.

---

## **9. Arredondamento de Notas**

**Descrição:**  
Suponha que um aluno obteve as seguintes notas: `8.6`, `7.4`, `9.1` e `6.8`. Use a função `round()` para **arredondar cada nota** para o inteiro mais próximo e calcule a **média** das notas arredondadas.

**Dicas:**
- Armazene as notas em uma lista.
- Após arredondar, some as notas e divida pelo número de notas para obter a média.

---

## **10. Calculadora de IMC (Índice de Massa Corporal)**

**Descrição:**  
Escreva um programa que solicite ao usuário seu **peso** (em kg) e **altura** (em metros), calcule o **IMC** usando a fórmula:

```
IMC = peso / (altura ** 2)
```

Use **operadores de comparação** para informar se o usuário está **abaixo do peso**, **peso normal**, **sobrepeso** ou **obeso**, de acordo com a tabela abaixo:

- Abaixo de 18.5: Abaixo do peso
- Entre 18.5 e 24.9: Peso normal
- Entre 25.0 e 29.9: Sobrepeso
- Acima de 30.0: Obeso

**Dicas:**
- Utilize estruturas condicionais para verificar em qual faixa o IMC calculado se enquadra.
- Exiba o IMC com uma casa decimal.