<a href="https://colab.research.google.com/github/MathMachado/DSWP/blob/master/Notebooks/NB03__Numeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notas & observações


___
# **Agenda**:
> Nesta capítulo, vamos falar sobre:

* Operadores aritméticos
* Funções round(), floor(), ceil() e trunc()
* Operadores para comparação
* Operadores de atribuição
* Wrap Up
* Exercícios

# **Números**
> Basicamente, há dois tipos de números em Python:

* float point
    * Exemplo: temperatura, altura, etc
    
* Integer
    * Exemplo: idade, dia do mês, etc...


___
# **Operadores Aritméticos**
> Considere as variáveis A= 7 e B= 3 abaixo, então:

| Operador | Descrição | Exemplo | Operação | Resultado |
|---|---|---|---|---|
| +  | Adição | C= A+B | C= 7+3 | C= 10 |
| -  | Subtração | C= A-B | C= 7-3 | C= 4|
| /  | Divisão | C= A/B | C= 7/3 | C= 2.333... |
| %  | Resto da Divisão | C= A%B | C= 7%3 | C= 1 | 
| *  | Multiplicação | C= A*B | C= 7*3 | C= 21 |
| //  | Quociente da Divisão | C= A//B | C= 7//3 | C= 2 |
| **  | Potência | C= A**B | C= 7\*7\*7 | C= 343|

> Nas operações matemáticas de divisão, chamamos:

    * 7 de dividendo (o número que se quer dividir);
    * 3 de divisor;
    * 2 é o quociente ou resultado, dado por 7//3;
    * 1 é o resto, dado por 7%3

Confirma na imagem a seguir os elementos da Divisão:

![Divisao](https://github.com/MathMachado/Materials/blob/master/Divisao.png?raw=true)

Conforme vimos acima, temos que A= 7 e B= 3. Vamos aplicar os conhecimentos que acabamos de aprender:

In [0]:
A= 7
B= 3

Qual o valor de C nas expressões abaixo?

In [0]:
C= A+B
f'O valor de C é: {C}'

'O valor de C é: 10'

In [0]:
C= A-B
f'O valor de C é: {C}'

'O valor de C é: 4'

In [0]:
C= A*B
f'O valor de C é: {C}'

'O valor de C é: 21'

## Funções round(), floor(), ceil() e trunc()

### Exemplo 1

In [0]:
C= B/A

# Importa a biblioteca math
import math

C_round2= round(C, 2) # Arredonda C para 2 casas decimais.
C_round4= round(C, 4) # Arredonda C para 4 casas decimais.
C_floor= math.floor(C) # Retorna o maior valor inteiro menor ou igual a C.
C_ceil= math.ceil(C) # Retorna o menor valor inteiro maior ou igual a C.
C_trunc= math.trunc(C) # Retorna o valor Real C truncado para um inteiro

In [0]:
# Valor de C com 17 casas decimais:
f'{C}'

'0.42857142857142855'

In [0]:
# Valor de C com 2 casas decimais:
f'{C_round2}'

'0.43'

In [0]:
# Valor de C com 4 casas decimais:
f'{C_round4}'

'0.4286'

In [0]:
# Retorna o maior valor inteiro menor ou igual a C:
f'{C_floor}'

'0'

In [0]:
# Retorna o menor valor inteiro maior ou igual a C:
f'{C_ceil}'

'1'

In [0]:
# Retorna a parte inteira de C:
f'{C_trunc}'

'0'

### Exemplo 2

In [0]:
C= 13/3

# Importa a biblioteca math
import math

C_round2= round(C, 2) # Arredonda C para 2 casas decimais.
C_round4= round(C, 4) # Arredonda C para 4 casas decimais.
C_floor= math.floor(C) # Retorna o maior valor inteiro menor ou igual a C.
C_ceil= math.ceil(C) # Retorna o menor valor inteiro maior ou igual a C.
C_trunc= math.trunc(C) # Retorna o valor Real C truncado para um inteiro

... Novamente, mas desta vez, definindo 2 casas decimais:

In [0]:
f'O valor de C é: {C:{8}.{2}}'

'O valor de C é:      4.3'

In [0]:
# Valor de C com 2 casas decimais:
f'{C_round2}'

'4.33'

In [0]:
# Valor de C com 4 casas decimais:
f'{C_round4}'

'4.3333'

In [0]:
# Retorna o maior valor inteiro menor ou igual a C:
f'{C_floor}'

'4'

In [0]:
# Retorna o menor valor inteiro maior ou igual a C:
f'{C_ceil}'

'5'

In [0]:
# Retorna a parte inteira de C:
f'{C_trunc}'

'4'

___
# **Operadores de Comparação**

* Considere as variáveis A= 7, B= 3 e o vetor x abaixo, então:

| Operador | Exemplo | Descrição | Resultado |
|---|---|---|---|
| == | A == B | 7 é igual a 3? | False |
| != | A != B | 7 é diferente de 3? | True |
| >  | A > B | 7 é maior que 3? | True |
| < | A < B | 7 é menor que 3? | False | 
| >=  | A >= B | 7 é maior ou igual a 3? | True |
| <= | A <= B | 7 é menor ou igual a 3? | False |

Vamos aplicar os conhecimentos que acabamos de aprender:

In [0]:
A= 7
B= 3

Vetor x:

In [0]:
import numpy as np
x= np.array([0,1,2,3,4,5,6,7,8,9])

Qual o resultado para C nas expressões a seguir:

In [0]:
A == B

In [0]:
A != B

In [0]:
A > B

In [0]:
A < B

In [0]:
A >= B

In [0]:
A <= B

Qual o resultado das expressões a seguir:

In [0]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [0]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [0]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [0]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Da mesma forma, se tivermos a matrix abaixo:

In [0]:
r= np.random.RandomState(20111974)
x= r.randint(10, size= (3,4))
x

array([[8, 8, 2, 8],
       [9, 1, 8, 0],
       [4, 2, 0, 8]])

Qual o resultado das expressões a seguir:

In [0]:
x == 3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [0]:
x != 3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [0]:
x < 3

array([[False, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False]])

In [0]:
x > 3

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True]])

___
# **Operadores de Atribuição**

| Operador | Exemplo | Operação Equivalente | 
|---|---|---|
| = | C= A+B |
| += | C+= B | C= C+B |
| -= | C-= B | C= C-B |
| *= | C*= B | C= C*B |
| /= | C/= B | C= C/B |
| %= | C%= B | C= C%B |
| **= | C**= B | C= C**B |
| //= | C//= B | C= C//B |

Considere A= 7 e B= 3 e vamos praticar os conhecimentos que acabamos de aprender:

In [0]:
A= 7
B= 3

Qual o valor de C nas expressões a seguir:

In [0]:
C = A + B
f'O valor de C é: {C}'

In [0]:
C += A
f'O valor de C é: {C}'

In [0]:
C -= A
f'O valor de C é: {C}'

In [0]:
C *= A
f'O valor de C é: {C}'

In [0]:
C /= A
f'O valor de C é: {C}'

In [0]:
C %= A
f'O valor de C é: {C}'

In [0]:
C **= A
f'O valor de C é: {C}'

In [0]:
C //= A
f'O valor de C é: {C}'

___
# **Wrap Up**

___
# Exercícios