<a href="https://colab.research.google.com/github/MathMachado/Python_RFB/blob/DS_Python/Notebooks/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Melhorias da sessão
* Qual a interpretação para os autovalores e autovetores?
* Geração de números aleatórios usando numpy;

# Numpy
* O NumPy é um pacote para computação científica e algebra linear para Python.

![Numpy](https://github.com/MathMachado/Python_RFB/blob/master/Material/numpy_basics-1.png?raw=true)

In [0]:
# Librarie NumPy
import numpy as np
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

# Exemplos

## Criar um Vetor

In [0]:
MyVector= np.array([0,1,2,3,4,5,6,7,8,9])
MyVector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Soma 2 à cada item de MyVector:
MyVector2= MyVector+2
MyVector2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
# Multiplicar por 10 cada item de MyVector:
MyVector3= MyVector*10
MyVector3

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Criar uma Matriz

In [0]:
# Criar uma matrix com 2 linhas e 3 colunas usando números aleatórios
np.random.seed(20111974)
MyMatrix= np.random.randn(2, 3)

MyMatrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
MyMatrix

array([[2.5063, 1.1144, 2.0557],
       [0.5648, 0.299 , 1.0493]])

In [0]:
# Número de linhas e colunas de MyMatrix
MyMatrix.shape

(2, 3)

In [0]:
MyMatrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# Número de linhas e colunas de MyMatrix2
MyMatrix2.shape

(3, 3)

In [0]:
# Somar 2 à cada elemento de MyMatrix
MyMatrix1_2= MyMatrix+2
MyMatrix1_2

array([[4.5063, 3.1144, 4.0557],
       [2.5648, 2.299 , 3.0493]])

In [0]:
# Multiplicar por 10 cada elemento de MyMatrix
MyMatrix1_3= MyMatrix*10
MyMatrix1_3

array([[25.0628, 11.144 , 20.5566],
       [ 5.6482,  2.9897, 10.4931]])

## Selecionar itens

In [0]:
# Selecionar o segundo item de MyVector:
MyVector[1]

1

In [0]:
# Selecionar o item da linha 2, coluna 3 da Matriz MyMatrix2:
MyMatrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
MyMatrix2[1,2]

6

In [0]:
# Selecionar o último elemento de MyVector
MyVector[-1]

9

## Aplicar funções como max(), min()

In [0]:
f'O máximo de MyVector é: {np.max(MyVector)}'

'O máximo de MyVector é: 9'

In [0]:
f'O mínimo de MyVector é: {np.min(MyVector)}'

'O mínimo de MyVector é: 0'

In [0]:
f'O máximo de MyMatrix2 é: {np.max(MyMatrix2)}'

'O máximo de MyMatrix2 é: 9'

In [0]:
f'O máximo de cada LINHA de MyMatrix2 é: {np.max(MyMatrix2, axis= 1)}' # Aqui, axis= 1 é que diz ao numpy que estamos interessados nas linhas

'O máximo da linha 2 de MyMatrix2 é: [3 6 9]'

In [0]:
f'O máximo de cada COLUNA de MyMatrix2 é: {np.max(MyMatrix2, axis= 0)}' # axis= 0, diz ao numpy que estamos interessados nas colunas.

'O máximo de cada COLUNA de MyMatrix2 é: [7 8 9]'

## Calcular média, variância e desvio-padrão

In [0]:
f'A média de MyVector é: {np.mean(MyVector)}'

'A média de MyVector é: 4.5'

In [0]:
f'A média de MyMatrix2 é: {np.mean(MyMatrix2)}'

'A média de MyMatrix é: 5.0'

In [0]:
f'O Desvio Padrão de MyMatrix2 é: {np.std(MyMatrix2)}'

'O Desvio Padrão de MyMatrix2 é: 2.581988897471611'

## Reshaping
* Nossa matriz MyMatrix2 tem a seguinte forma:

In [0]:
MyMatrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# reshaping para 9 linhas e 1 coluna:
MyMatrix2.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Matriz Transposta

In [0]:
MyMatrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
MyMatrix2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Autovalores e Autovetores

In [0]:
MyMatrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
autovalores, autovetores= np.linalg.eig(MyMatrix2)

In [0]:
autovalores

array([16.1168, -1.1168, -0.    ])

In [0]:
autovetores

array([[-0.232 , -0.7858,  0.4082],
       [-0.5253, -0.0868, -0.8165],
       [-0.8187,  0.6123,  0.4082]])

# Exercícios